### ISSUE TITLE
Project health?

### ISSUE THREAD

**Issue by fuzzy76** [bergie/hallo#247]
Is this project still active? I am evaluating WYSIWYG-components for an upcoming project, but 12 open pull requests and no commits for a year does not look promising...

**Comment by bergie** [comment]
At least right now I'm unable to work on this project. This may change in the future. But for now, if somebody would like to take the maintainership over, I'd be happy to help with the transition

**Comment by grobmeier** [comment]
@bergie I am interested to do that. I have worked with Hallo before, and since then I even learned how to submit good pull requests ;-) I am also experienced with Open Source (doing stuff at Apache)

Actually I need Hallo in near future, especially the Markdown features. I was considering to fork and disconnect, but keeping the stuff together would be more of my preference. Let me know if you would to have me step up.

**Comment by bergie** [comment]
@grobmeier awesome! Can you drop me [an email](http://bergie.iki.fi/about/) and we can handle the handover

**Comment by bergie** [comment]
I'm happy to announce that @grobmeier has taken over the maintainership of this project
